# fly.toml file generated for u2k on 2023-03-22T19:26:43+01:00

app = "u2k"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_URL = "https://u2k.fly.dev/"
  TERMII_KEY = "TLr990qdBhwDFgxDmSBt8AqWHjxPbjooOTxZZzkdu4brhEItvelLpiurQo1Wks"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  #DB
  DB_CONNECTION="mysql"
  DB_HOST="eu-west.connect.psdb.cloud"
  DB_PORT=3306
  DB_DATABASE="u2k"
  MYSQL_ATTR_SSL_CA="/etc/ssl/certs/ca-certificates.crt"

# File: fly.toml
[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:work"


[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
